### ISSUE TITLE
[1.18.2 Forge v2.2] World generation is the same in every world, despite the seed being different

### ISSUE THREAD

**Issue by freeeezin** [Apollounknowndev/tectonic#84] opened 2024-01-18 01:53 UTC
Using v2.2. World is the same in every seed and only structures and features change between worlds. Identical to issue #62. I even get the same world as them.

![2024-01-17_19 43 35](https://github.com/Apollounknowndev/tectonic/assets/156977112/b2f30427-b6ea-4629-af34-fc1bc5ccdb19)
![2024-01-17_19 44 33](https://github.com/Apollounknowndev/tectonic/assets/156977112/af77a71a-174f-4ea7-b233-f9d86bb7fa3f)
![2024-01-17_19 45 27](https://github.com/Apollounknowndev/tectonic/assets/156977112/c23943fc-ecd3-4e74-a000-59bf7f99ce19)

**Comment by thelyric27** [comment] 2024-01-18 02:26
![photo_2024-01-17_20-14-41](https://github.com/Apollounknowndev/tectonic/assets/103123904/c97d5c6f-2e8c-4995-9700-d9c2bfc454c4)

Hi, your world doesn't happen to have a mountain range across that ravine and a lake with an island in the middle of to the right does it?... I might have the exact same world and issue haha. Even playing with a ton of different mods, but I hadn't added any other ones specifically for worldgen yet. I'm on the same Minecraft, Forge, and mod versions otherwise. I was so confused and got hit with hard deja vu while i was generating different worlds to test Distant Horizons with XD

This wasn't a problem in my 1.19.2 modpack, and it's still beautiful but it's very strange how they all generated almost exactly the same. I hope this gets fixed because I normally love this mod, despite how long it takes chunks to generate sometimes (just use Chunk Pregenerator, it worked very well with a large and diverse list of mods.)

**Comment by freeeezin** [comment] 2024-01-18 02:50
@thelyric27 In fact, yes you and I both have the same issue, just with different biomes thanks to your modlist. I originally ran this mod alongside a long list of mods that added new biomes, similar to you.

This issue supposedly does not occur on 1.19+ versions of the mod and has actually been reported previously by other users. Unfortunately, it seems the issue has returned.

**Comment by freeeezin** [comment] 2024-01-18 02:50
Fat-fingered the close button whoops

**Comment by thelyric27** [comment] 2024-01-18 05:35
> Fat-fingered the close button whoops

Excellent work ( ͡° ͜ʖ ͡°)

In all seriousness though I came back to say I'd gotten the pregenerator mixed up, the one I would actually recommend to use with this and other worldgen-heavy mods was Chunky. It's actually subtle enough that you can still play the game while you explore your spawn area. Extra nice if you use village spawn point mod since you'll spend the pregen time looting and checking out the village :)

**Comment by NolanHewitt** [comment] 2024-01-18 07:17
seems like this even effects superflat generation as well

**Comment by Y1rd** [comment] 2024-01-23 04:56
I can confirm this is once again an issue. The modrinth page states the Forge version needs Unfixed Seeds despite there being no forge version of that mod.
@Apollounknowndev

**Comment by Apollounknowndev** [comment] 2024-03-13 02:38
Fixed in v2.2.1.

**Closed** 2024-03-13 07:04 UTC
Labels: bug, in progress
