### ISSUE TITLE
Request adding compatibility to 'Regions Unexplored'

### ISSUE THREAD

**Issue by Hakuyako** [Apollounknowndev/tectonic#91] opened 2024-01-28 14:10 UTC
When I use Regions Unexplored + Tectonic V2.2, the generation of continents and oceans looks like "merge" together.

The game recognizes the area belongs to the continental biome, however the generation of the terrain is completely ocean. The surface is come up with ocean and the land structures are floating on the surface.

This problem did not happen by accidental, it almost exists in any ocean region, 

![image](https://github.com/Apollounknowndev/tectonic/assets/100094927/7e09f789-c867-417c-9625-065147522c50)

![image](https://github.com/Apollounknowndev/tectonic/assets/100094927/3aa282da-1c80-4e6b-976c-fcf916621b96)

I'm using these these mods to make a modpack, please help me fix these features, if you need any further information please just tell me, appreciate.

**Comment by grugsy** [comment] 2024-01-29 07:55
First time I've seen this happen and it not be a mushroom biome variant. Related to #90.

**Comment by SanguineWaters** [comment] 2024-02-13 22:25
Strange, I haven't experienced your situation except for a one off situation with a very small ashen woodland biome 4-10? blocks bellow the surface. The biome was probably no larger than a 20x20 area, and I have Regions unexplored and tectonic installed. I have only seen that twice maybe. Could it be the terrablender, forge, or regions unexplored versions? Please let us know what versions you have and if there are any other mods that might impact world gen.

**Mods**
Forge 1.20.1-47.2.20
BiomesOPlenty-1.20.1-18.0.0.598
RegionsUnexploredForge-0.5.3.1+1.20.1
tectonic-mod-1.19.3-v2.2
TerraBlender-forge-1.20.1-3.0.1.2

**Edited Configs** for Terrablender and RU were originally .toml, I don't know if this impacts world gen significantly but here it is incase.
[ru-common.txt](https://github.com/Apollounknowndev/tectonic/files/14272823/ru-common.txt)
[ru-primary-region.txt](https://github.com/Apollounknowndev/tectonic/files/14272824/ru-primary-region.txt)
[ru-secondary-region.txt](https://github.com/Apollounknowndev/tectonic/files/14272825/ru-secondary-region.txt)
[terrablender.txt](https://github.com/Apollounknowndev/tectonic/files/14272832/terrablender.txt)

**Comment by grugsy** [comment] 2024-02-14 07:57
It's explained in my related issue. It's the way terrablender works. Terrablender places biomes based on default overworld generation parameters. anything that changes parameter points, or doesn't fill a parameter range will result in unwanted behavior.

**Comment by zoqin** [comment] 2024-02-20 10:00
i experienced similar issue

**Comment by Apollounknowndev** [comment] 2024-03-13 02:30
Duplicate of #70, to be fixed in v2.2.1

**Closed by Apollounknowndev** 2024-03-13 02:30 UTC
