### ISSUE TITLE
Ocean monuments

### ISSUE THREAD

**Issue by JianhuiDong9999** [Apollounknowndev/tectonic#98] opened 2024-03-05 19:57 UTC
Due to the lowering of the ocean floor, ocean monuments now have very tall supporting pillars instead of lowering themselves down to the new ocean level.
![Uploading Screenshot 2024-03-05 at 11.52.01 AM.png…]()

**Comment by Apollounknowndev** [comment] 2024-03-05 23:51
Duplicate of #74, can't fix.

**Closed by Apollounknowndev** 2024-03-05 23:51 UTC
