### ISSUE TITLE
Forge 1.18.2 Tectonic and Terralith Invalid Data pack.

### ISSUE THREAD

**Issue by unparted** [Apollounknowndev/tectonic#129] opened 2024-04-09 00:05 UTC
I am using the mod versions of both and tested with different forge versions. I believe that the Terratonic datapack seems to be causing the issue because when I load Tectonic without Terralith it works and vice versa. My game says that the Terratonic pack is made for a newer version of the game, I even tried downgrading Tectonic and Terralith, same issue. 
![image](https://github.com/Apollounknowndev/tectonic/assets/87347650/7c6675ea-38a8-4d76-bbe5-ef8d8912accc)

My mods folder: 
![image](https://github.com/Apollounknowndev/tectonic/assets/87347650/7f1529d3-d3c6-4f5f-9c93-a0093d1b602f)

If you could not already tell, I'm using prism launcher, but I fail to see how prism would be an issue. My game does not crash it just says invalid data pack and for some reason I can not start it in safe mode. 
[latest.log](https://github.com/Apollounknowndev/tectonic/files/14911931/latest.log)

If you need any additional information please lmk.

**Comment by taitep** [comment] 2024-04-09 14:08
I have the same issue, also happen to use Prism. I do not have a solution though.

**Comment by unparted** [comment] 2024-04-09 14:51
Thanks for verifying @taitep. I have tried with Curseforge and the issue is still present, so its not the launcher.

**Comment by Apollounknowndev** [comment] 2024-04-09 21:12
What exactly isn't working? The pack saying it's for a newer version doesn't necessarily mean it doesn't work.

**Comment by unparted** [comment] 2024-04-09 21:28
Yeah, but I did not download the datapack and I'm using the 1.18.2 version of the mod, so shouldn't it download the 1.18.2 version of the data pack? Is it even possible to get Tectonic and Terralith working together on 1.18.2 forge?

**Comment by Apollounknowndev** [comment] 2024-04-09 23:18
The outdated pack error does not matter as long as the game runs as intended. When you create a new world, what happens?

**Comment by unparted** [comment] 2024-04-10 01:02
I cant create a new world at all, the game gives me this message 
![image](https://github.com/Apollounknowndev/tectonic/assets/87347650/4300b1ab-3b52-42b8-a268-cf1852021869)
and I click "safe mode" but nothing happens.

**Comment by Apollounknowndev** [comment] 2024-04-10 01:44
Fixed in v2.3.4a.

**Closed by Apollounknowndev** 2024-04-10 01:44 UTC
Labels: bug, compatibility, crash
