### ISSUE TITLE
Water transition generation still remains broken

### ISSUE THREAD

**Issue by JoeyHamlet** [Apollounknowndev/tectonic#144] opened 2024-05-02 18:50 UTC
This issue has frustrated me for a while, realising that it remained unresolved in #56 but  was supposedly fixed in #55, #46 made me want to report my findings as whilst it's claimed that it has been fixed since 2.1.1 it hasn't been so in my experience. 

Minecraft 1.20.1
Fabric 0.15.10
Fabric API 0.92.1

Mods:
Indium 1.0.30+mc1.20.4
Lithium mc1.20.1-0.11.2
Mod Menu 7.2.2
Reese's Sodium Options mc1.20.1-1.7.2
Sodium mc1.20.1-0.5.8
Sodium Extra mc1.20.1-0.5.4
**Tectonic 2.3.4**

Seed: -3267759561548726880
Swamp water generation breaks frequently
![2024-05-02_20 26 44](https://github.com/Apollounknowndev/tectonic/assets/43111443/c7c8f05e-12b6-4b2c-8458-2566eefb5f66)
![2024-05-02_20 49 21](https://github.com/Apollounknowndev/tectonic/assets/43111443/cf013860-8ffa-4d26-9f16-83eb14eb240a)

**Comment by JoeyHamlet** [comment] 2024-05-02 18:57
This kind of terrain generation issue isn't exclusive to Swamp biomes, it will also happen less frequently along river banks in any other biome.

Examples from the same seed: (-3267759561548726880)

Taiga:
![2024-05-02_20 27 32](https://github.com/Apollounknowndev/tectonic/assets/43111443/bef36680-dc0b-4f90-a4bb-33359d140a0a)
![2024-05-02_20 28 07](https://github.com/Apollounknowndev/tectonic/assets/43111443/776e0e64-5c69-4857-92aa-4ae92dfae25f)

Savanna:
![2024-05-02_20 55 14](https://github.com/Apollounknowndev/tectonic/assets/43111443/1b42dbbc-44c5-4ff0-8a78-93eaf66d87f0)

Plains:
![2024-05-02_20 55 52](https://github.com/Apollounknowndev/tectonic/assets/43111443/e08e8dc8-3d29-45c8-a23f-45024dac808f)

**Comment by JoeyHamlet** [comment] 2024-05-02 19:02
Coords just for copy paste in order of the screenshots provided so far:

Swamp 1: -97 83 -828
Swamp 2: -1610 83 3166
Taiga 1: -641 64 -852
Taiga 2: -760 72 -966
Savanna 1: -8330 70 9698
Plains 1: -8383 89 10252

**Comment by Apollounknowndev** [comment] 2024-05-02 19:20
Duplicate of #56

**Closed** 2024-05-02 19:20 UTC
