### ISSUE TITLE
Terralith Biomes either flat, submerged or unable to generated properly

### ISSUE THREAD

**Issue by rhongobongo** [Apollounknowndev/tectonic#102] opened 2024-03-13 14:21 UTC
One of the problematic biomes from Terralith is the Haze Mountain. They are mostly submerged or flat with minimal trees.

#65 , #52

**Comment by Apollounknowndev** [comment] 2024-03-15 07:07
Duplicate of #65

**Closed by Apollounknowndev** 2024-03-15 07:07 UTC
