### ISSUE TITLE
Can't generate superflat worlds

### ISSUE THREAD

**Issue by vlad1m** [Apollounknowndev/tectonic#94] opened 2024-02-10 16:08 UTC
On forge, minecraft version 1.20.1, mod version 2.2, despite the world type being superflat, the game will still generate a regular world.
I'm using a large modpack of 263 mods, but the only mods that alter world generation are: several structure mods; Biome makeover; Continents; Farmers delight; Galosphere;  geophilic; hearths; Snow under trees; twigs.

**Comment by NolanHewitt** [comment] 2024-02-12 04:32
The same happens on fabric as well

**Comment by ionutsoran** [comment] 2024-02-20 10:45
I can confirm this on forge version 1.20.1 as well for tectonic 2.2

**Comment by Otateriheem** [comment] 2024-03-05 14:01
I had the same problem, to fix it when creating you world, go in in the "more" tab then in "datapacks" and remove Tectonic from the "selected" tab.
You can now use the vanilla world types?

**Comment by MageOfGaming** [comment] 2024-03-12 23:58
This is actaully the same bug i had, thw reason why that happens is because it generates the same world again and again with miniscule differences

**Comment by Apollounknowndev** [comment] 2024-03-13 02:41
Duplicate of #80, fixed in v2.2.1.

**Closed by Apollounknowndev** 2024-03-13 02:41 UTC
