### ISSUE TITLE
Tropicraft 1.20.1 Dimension Incompatible with Tectonic v2.2

### ISSUE THREAD

**Issue by SanguineWaters** [Apollounknowndev/tectonic#93] opened 2024-02-06 02:59 UTC
### Describe the bug
When attempting to access the Tropicraft dimension, the player is stuck in the void with no visible terrain generating for 13 minutes before the game crashes. Upon reloading the world, the world is saved the moment before the attempt to access the dimension.

### To Reproduce
Use Tropicraft-9.6.3 (1.20.1), Forge 1.20.1-47.2.20, and Tectonic 1.19.3-v2.2
Grab a chair from Tropicraft, and a Piña Colada (search up Colada unless you have a Spanish keyboard)
Place the chair down
Set the world to night "/time set night" and quickly drink the Piña Colada by right clicking it
Then it attempts to create and enter the dimension and crashes

[crash-2024-02-05_20.14.55-server.txt](https://github.com/Apollounknowndev/tectonic/files/14174104/crash-2024-02-05_20.14.55-server.txt)

Sorry If this is a duplicate of another post, I provided the crash log and more to make it easier hopefully. I'm new to this so forgive me for any errors. This mod is amazing.

### Update Feb 6, attempts to get it to work/investigate
I tried 8gb of allocated ram instead of 10gb (As suggested by someone in the Tropicraft discord), with the smallest render distance with Tectonic, crash still happened when attempting to create and join the dimension
[crash-2024-02-06_12.51.25-server.txt](https://github.com/Apollounknowndev/tectonic/files/14187081/crash-2024-02-06_12.51.25-server.txt)

Then I tried it with ferrite core (reduces ram usage,(As suggested by someone in the Tropicraft discord) and that didn't work. 
Tried it without ferrite core and Tectonic and the dimension generated.
I then reload Minecraft with Tectonic added and the world instantly goes to 90%+ ram usage instantly in the dimension with a render distance of 12 now.
Added Ferrite Core with Tectonic and same thing, 90%+ ram usage.
Something with Tectonic makes generating the dimension impossible if installed before generating it and eventually use up all available ram. And if it is installed after, it uses up all the all of the ram again but instantly.

**Comment by Mecheon** [comment] 2024-02-24 01:34
Just to note on this one, experiencing same error

When using Tropicraft with other world overhauls (Tested specifically with Continents, Terralith and Ecospherical Expansion), Tropicraft uses that particular generation, showing that it relies on the standard Minecraft generation and whatever overrides it. Something particular to Tectonic is causing the error, as it normally supports the other generation methods

**Comment by Apollounknowndev** [comment] 2024-03-13 02:32
Duplicate of #58

**Closed by Apollounknowndev** 2024-03-13 02:32 UTC
