### ISSUE TITLE
Scuffed generation near bodies of water {Forge 1.20.1 - v2.3.4}

### ISSUE THREAD

**Issue by JimBob-bb** [Apollounknowndev/tectonic#142] opened 2024-04-30 18:08 UTC
When using biome mods such as ''biomes o' plenty'', when there is a body of water and a non vanilla biome meeting it, it ends up in a scuffed generation.
<img width="1248" alt="2024-04-30_18 52 25" src="https://github.com/Apollounknowndev/tectonic/assets/165731241/964318ef-9c39-4edb-8159-b7f775c66cbb">
If you are aware of a simple way I could fix this without removing the biome mods, that would be great.

**Comment by JoeyHamlet** [comment] 2024-05-02 19:12
This issue persists even with vanilla biomes in my experience.

**Comment by Apollounknowndev** [comment] 2024-05-02 19:20
Duplicate of #56

**Closed by Apollounknowndev** 2024-05-02 19:20 UTC
